target-version = "py310"
# Set the maximum line length to 120
line-length = 120
[lint]
select = ["ALL"]
extend-select = ["E501"]
ignore = ["TD", "FIX002", 
          "TRY003",             # exception handling
          "D105", "D400",       # docstring style issues
          "PTH",                # until we migrate to Pathlib
          "T201", "G004", # logging currently ignored
          "S603", "S607", # subprocess security issues
         ]
[lint.pydocstyle]
convention = "pep257"