services:
  
  add_branch_and_create_pr:
    image: nmrlipids/core
    command: |
      /bin/bash -c "
      # Clone the main repository
      git clone https://x-access-token:$${GITHUB_TOKEN}@github.com/$${GITHUB_REPOSITORY}.git Databank &&
      cd Databank &&
      
      # Fetch the PR branch from the fork and create a new branch based on it:
      git fetch origin pull/$${PR_NUMBER}/head:$${BRANCH_NAME} &&
      git checkout $${BRANCH_NAME} &&
          
      # Set Git username and email
      Scripts/DockerScripts/RunnerGitConfig.sh &&

      # Push the new branch to the main repository
      git push https://x-access-token:$${GITHUB_TOKEN}@github.com/$${GITHUB_REPOSITORY} $${BRANCH_NAME}:$${BRANCH_NAME} &&

      #Create pr:
      gh pr create --head $${BRANCH_NAME} --base $${TARGET_BRANCH_NAME} --title \"$${GITHUB_ACTOR}'s New Data\" --body \"This PR brings in new data from $${GITHUB_ACTOR}\"
      "
          
  recompute_databank:
    image: nmrlipids/core
    command: |
      /bin/bash -c "
      git clone https://x-access-token:$${GITHUB_TOKEN}@github.com/$${GITHUB_REPOSITORY}.git --branch=$${BRANCH_NAME} Databank &&
      cd Databank &&
      python Scripts/DockerScripts/DispatchRecompute.py
      "

  recompute_instance:
    image: nmrlipids/core
    command: |
      /bin/bash -c "
      source /usr/local/gromacs/bin/GMXRC &&
      git clone https://x-access-token:$${GITHUB_TOKEN}@github.com/$${GITHUB_REPOSITORY}.git Databank &&
      cd Databank &&
      git fetch origin &&
      git branch -r &&
      git checkout $${BRANCH_NAME} &&
      Scripts/DockerScripts/RecomputeSimdata.sh
      "

  tests:
    image: nmrlipids/core
    command: |
      /bin/bash -c "
      git clone --branch $${BRANCH_NAME} https://github.com/MagnusSletten/Databank.git /app/Databank &&
      cd /app/Databank/Scripts/tests/ &&
      source /usr/local/gromacs/bin/GMXRC &&
      "

  add_data:
    image: nmrlipids/core
    command: |
      /bin/bash -c "
      source /usr/local/gromacs/bin/GMXRC &&
      git clone https://x-access-token:$${GITHUB_TOKEN}@github.com/MagnusSletten/Databank.git --branch=$${BRANCH_NAME} Databank &&
      cd Databank &&
      Scripts/DockerScripts/RunnerGitConfig.sh &&
      Scripts/DockerScripts/GetNewExperimentData.sh &&
      Scripts/DockerScripts/GetNewSimData.sh
      "
