name: Add data 

on:
  workflow_call:
    inputs:
      working_branch_name:
        description: "The new branch where new files are added"
        required: true
        default: "default"
        type: string 
      target_branch_name:
        description: "The final destination for files. This will be main at the end"
        required: true
        default: "default"
        type: string 
  workflow_dispatch:
    inputs:
      working_branch_name:
        description: "The new branch where new files are added"
        required: true
        default: "default"
      target_branch_name:
        description: "The final destination for files. This will be main at the end"
        required: true
        default: "default"

jobs:
  AddData:
    runs-on: nrec-large
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pull and run Docker Compose
        working-directory: ./Docker  # Navigate to the Docker directory where compose.yml is located
        run: |
              sudo docker compose pull add_data
              sudo docker compose run --rm \
                -e REPO_URL=https://github.com/MagnusSletten/Databank.git \
                -e BRANCH_NAME=bot/info_yaml_20241106101755 \
                -e GITHUB_TOKEN=*** \
                -e TARGET_BRANCH=dev_pipeline_compose \
                add_data
