name: Add data 

on:
  workflow_call:
    inputs:
      working_branch_name:
        description: "Branch containing new data:"
        required: true
        type: string 
      target_branch_name:
        description: "Branch to compare against for identifying new files:"
        required: true
        type: string 
  workflow_dispatch:
    inputs:
      working_branch_name:
        description: "Branch containing new data:"
        required: true
      target_branch_name:
        description: "Branch to compare against for identifying new files:"
        required: true


jobs:
  DockerCleanup:
    uses: MagnusSletten/Databank/.github/workflows/DockerCleanup.yml@dev_pipeline_rebase_clean
    with:
      delete_images: false

  AddData:
    needs: DockerCleanup
    runs-on: nrec-large
    steps:
      - name: Pull Docker image
        run: |
            sudo docker pull nmrlipids/core
      
      - name: Computing new data
        run: |
            sudo docker run --rm \
              -e GITHUB_REPOSITORY="${{ github.repository }}" \
              -e BRANCH_NAME="${{ inputs.working_branch_name}}" \
              -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
              -e TARGET_BRANCH="${{ inputs.target_branch_name }}" \
              -e TQDM_DISABLE=True \
              nmrlipids/core \
              /bin/bash -c "git pull && Scripts/WorkflowScripts/DockerRunInstructions/GetNewData.sh"

        
