name: Add data 

on:
  workflow_call:
    inputs:
      working_branch_name:
        description: "The new branch where new files are added"
        required: true
        default: "default"
        type: string 
      target_branch_name:
        description: "The final destination for files. This will be main at the end"
        required: true
        default: "default"
        type: string 
  workflow_dispatch:
    inputs:
      working_branch_name:
        description: "The new branch where new files are added"
        required: true
        default: "default"
      target_branch_name:
        description: "The final destination for files. This will be main at the end"
        required: true
        default: "default"

jobs:
  AddData:
    runs-on: nrec-large
    env:  
      REPO_URL: https://github.com/MagnusSletten/Databank.git
      BRANCH_NAME: ${{ inputs.working_branch_name }}  # Using the working branch input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_BRANCH: ${{ inputs.target_branch_name }}  # Using the target branch input

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pull and run Docker Compose
        working-directory: ./Docker
        shell: bash
        run: |
          # Export environment variables
          export REPO_URL="${{ env.REPO_URL }}"
          export BRANCH_NAME="${{ env.BRANCH_NAME }}"
          export GITHUB_TOKEN="${{ env.GITHUB_TOKEN }}"
          export TARGET_BRANCH="${{ env.TARGET_BRANCH }}"

          REPO_URL="${{ env.REPO_URL }}" \
          BRANCH_NAME="${{ env.BRANCH_NAME }}" \
          GITHUB_TOKEN="${{ env.GITHUB_TOKEN }}" \
          TARGET_BRANCH="${{ env.TARGET_BRANCH }}" \
          sudo docker compose run --rm add_data

          # Run docker compose with the environment variables set in the shell
          sudo docker compose run --rm add_data
