name: Add data 

on:
  workflow_call:
    inputs:
      working_branch_name:
        description: "The new branch where new files are added"
        required: true
        default: "default"
        type: string 
      target_branch_name:
        description: "The final destination for files. This will be main at the end"
        required: true
        default: "default"
        type: string 
  workflow_dispatch:
    inputs:
      working_branch_name:
        description: "The new branch where new files are added"
        required: true
        default: "default"
      target_branch_name:
        description: "The final destination for files. This will be main at the end"
        required: true
        default: "default"

jobs:
  AddData:
    runs-on: nrec-large
    env:  
      REPO_URL: https://github.com/MagnusSletten/Databank.git
      BRANCH_NAME: ${{ inputs.working_branch_name }}  # Using the working branch input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TARGET_BRANCH: ${{ inputs.target_branch_name }}  # Using the target branch input

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Pull and run Docker Compose
        working-directory: ./Docker
        shell: bash
        run: |
          echo "REPO_URL=${{ env.REPO_URL }}" >> .env
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}" >> .env
          echo "GITHUB_TOKEN=${{ env.GITHUB_TOKEN }}" >> .env
          echo "TARGET_BRANCH=${{ env.TARGET_BRANCH }}" >> .env
          sudo docker compose --env-file .env pull add_data
          sudo docker compose --env-file .env run --rm add_data
