name: Add experiment data

on:
  workflow_call:
    inputs:
      working_branch_name:
        description: "The new branch where new files are added"
        required: true
        default: "Magnus"
        type: string 
      target_branch_name:
        description: "The final destination for files. This will be main at the end"
        required: true
        default: "Magnus"
        type: string 

jobs:
  addExperimentData:
    runs-on: nrec-large
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.working_branch_name }}

      - name: Fetch target branch
        run: |
          git fetch origin ${{ inputs.target_branch_name }}
     
      - name: Check if new files exist in 'Data/Experiments'
        id: check
        run: |
          if git diff --name-only origin/${{ inputs.working_branch_name }} origin/${{ inputs.target_branch_name }} -- Data/experiments/; then
            echo "experiment_changed=true" >> $GITHUB_ENV
          else
            echo "experiment_changed=false" >> $GITHUB_ENV
          fi
        

      - name: Pull Docker image
        if: ${{env.experiment_changed == 'true'}} 
        run: |
          sudo docker pull nmrlipids/project:addexperiment1.0

      - name: Run the Docker container with environment variables
        if: ${{env.experiment_changed == 'true'}} 
        run: |
          sudo docker run --rm \
          --env REPO_URL=https://github.com/${{ github.repository }}.git \
          --env BRANCH_NAME=${{ inputs.working_branch_name }} \
          --env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          --env TARGET_BRANCH=${{ inputs.target_branch_name }} \
          nmrlipids/project:addexperiment1.0
