name: Handle Fork PRs

on:
  pull_request_target:
    branches:
      - new_pipeline_v2
    paths:
      - 'Scripts/BuildDatabank/info_files/**'

jobs:
  copy_fork_pr:
    runs-on: nrec-large
    steps:
      - name: Check if PR is from a fork
        id: check_fork
        run: |
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]]; then
            echo "This pull request is from the same repository. Skipping."
            exit 0
          else
            echo "This pull request is from a forked repository."
          fi

   
      - name: Fetch and checkout forked branch
        run: |
          git fetch https://github.com/${{ github.event.pull_request.head.repo.full_name }} ${{ github.event.pull_request.head.ref }}
          git checkout -b pr-${{ github.event.pull_request.number }}-from-fork FETCH_HEAD

 
      - name: Push the new branch
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} pr-${{ github.event.pull_request.number }}-from-fork:pr-${{ github.event.pull_request.number }}-from-fork

      - name: Fetch new branch
        run: |
           git fetch origin pr-${{ github.event.pull_request.number }}-from-fork
     
    
      - name: Authenticate gh
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

 
      - name: Create pull request
        run: |
          gh pr create --head pr-${{ github.event.pull_request.number }}-from-fork --base new_pipeline_v2 --title "Merge forked PR changes into new_pipeline_v2" --body "This PR merges changes from a forked repository into the new_pipeline_v2 branch."