name: Build documentation

on : workflow_dispatch

jobs:
    build-documentation:
        runs-on: ubuntu-latest 
        steps:
          - name: install depedencies
            run: |
                sudo apt update
                sudo apt-get install python3-sphinx 
                pip install myst-parser 
                pip install sphinx-rtd-theme
    
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
               ref: "dev_document_cicd"
       
          - name: build
            run: make html
            working-directory: Scripts/BuildDatabank/docs

          - name: Archive production artifacts
            uses: actions/upload-artifact@v4
            with:
                name: html-build
                path: Scripts/BuildDatabank/docs/build/html/*
        
    deploy-documentation:
        runs-on: ubuntu-latest
        needs: build-documentation
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                repository: "MagnusPriv/NMRLipids.github.io"

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: html-build
                path: .
                
            - name: Configure git
              run: |
               git config user.name 'github-actions[bot]'
               git config user.email 'github-actions[bot]@users.noreply.github.com'
            
            - name: Commit and push files
              run: |
                git add .
                git commit -m "Automated update of documentation"
                git push \
                https://x-access-token:${{ secrets.DOCUMENT_TOKEN }}@github.com/MagnusPriv/NMRLipids.github.io.git HEAD:push_test
            
            




