name: Build Docker Images
on:
  schedule:
    - cron: "0 4 1 * *"
  
  workflow_dispatch:

jobs:
  build_gromacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GROMACS repo
        uses: actions/checkout@v4
        with:
          repository: gromacs/gromacs
          fetch-depth: 0
          path: gromacs-src


      - name: Get previous tag
        id: tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with: 
          workingDirectory: gromacs-src
     
      - name: Strip leading 'v'
        id: version
        shell: bash
        run: |
            TAG="${{ steps.tag.outputs.tag }}"
            echo "version=${TAG#v}" >> "$GITHUB_OUTPUT"
        
      - name: Checkout Databank repo
        uses: actions/checkout@v4

      - name: Build gromacs image
        run: |
          docker build \
            -f Scripts/Docker/gromacs \
            -t nmrlipids/gromacs:${{ steps.tag.outputs.tag }} \
            --build-arg GROMACS_VERSION=${{ steps.version.outputs.version }} \
            .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push gromacs image
        run: |
          docker push nmrlipids/gromacs:${{ steps.tag.outputs.tag }}

  build_core:
    runs-on: ubuntu-latest
    needs: build_gromacs
    steps:
      - name: Checkout Databank repo
        uses: actions/checkout@v4

      - name: Build core image
        run: |
          docker build \
            -f Scripts/Docker/core \
            -t nmrlipids/core:latest \
            .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push core image
        run: |
          docker push nmrlipids/core:latest

