name: BuildDockerImages

on:
  workflow_dispatch:
    inputs:
      docker_image_name:
        description: "The Docker image name you want to rebuild and push to DockerHub (e.g., core)"
        required: true
      accept_failed:
        description: "The maximum number of acceptable failed tests"
        required: false
        default: "0"  # Default to 0 to stop on a single failure

jobs:
  build:
    runs-on: nrec-large
    steps:      
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: sudo docker build -t nmrlipids/${{ inputs.docker_image_name }} -f Docker/${{ inputs.docker_image_name }} .

      - name: Tag Docker Image
        run: sudo docker tag nmrlipids/${{ inputs.docker_image_name }} nmrlipids/${{ inputs.docker_image_name }}:latest

      - name: Test
        working-directory: ./Docker
        shell: bash
        run: |
          sudo docker compose run --rm \
            -e BRANCH_NAME="${{ github.head_ref }}" \
            -e ACCEPT_FAILED="${{ inputs.accept_failed }}" \
            tests