name: Build documentation

on : workflow_dispatch

jobs:
    build-documentation:
        runs-on: ubuntu-latest 
        steps:
          - name: install depedencies
            run: |
                sudo apt update
                sudo apt-get install python3-sphinx 
                pip install myst-parser 
                pip install sphinx-rtd-theme
    
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
               ref: "dev_document_cicd"
       
          - name: build
            run: make html
            working-directory: Scripts/BuildDatabank/docs
        
          




