name: BuildDockerImages

on:
  workflow_dispatch:
    inputs:
      docker_image_name:
        description: "The Docker image name you want to rebuild and push to DockerHub (e.g., add_data, recompute_instance, tests)"
        required: true

jobs:
  build_and_push:
    runs-on: nrec-large
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: sudo docker build -t nmrlipids/${{ inputs.docker_image_name }} -f Docker/${{ inputs.docker_image_name }} .

      - name: Push Docker image
        run: sudo docker push nmrlipids/${{ inputs.docker_image_name }}


     