name: Build documentation

on: 
  workflow_dispatch:
  push:
    branches: 
      - dev_document_cicd
    paths:
      - Scripts/**
    
jobs:
    build-documentation:
        runs-on: ubuntu-latest 
        steps:
          - name: install depedencies
            run: |
                sudo apt update
                sudo apt-get install python3-sphinx 
                pip install myst-parser 
                pip install sphinx-rtd-theme
    
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
               ref: "dev_document_cicd"
       
          - name: build
            run: make html
            working-directory: Scripts/BuildDatabank/docs

          - name: Archive production artifacts
            uses: actions/upload-artifact@v4
            with:
                name: html-build
                path: Scripts/BuildDatabank/docs/build/html/*
                retention-days: 1
        
    deploy-documentation:
        runs-on: ubuntu-latest
        needs: build-documentation
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                repository: "MagnusPriv/NMRLipids.github.io"
                ref: "push_test"   
                token: ${{ secrets.DOCUMENT_TOKEN }}     

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: html-build
                path: .
                
            - name: Commit and push documentation
              uses: EndBug/add-and-commit@v9
              with:
                author_name: github-actions[bot]
                author_email: github-actions[bot]@users.noreply.github.com
                message: "Automated update of documentation"
                    
            




