name: Process Info Files

on:
  workflow_call:
    inputs:
      start_clean_branch:
        description: "Branch containing new data:"
        required: true
        type: string 
      working_branch:
        description: "Contains workflow utilities to process files"
        required: true
        type: string 
  workflow_dispatch:
    inputs:
      start_clean_branch:
        description: "Branch containing new data:"
        required: true
      working_branch:
        description: "Contains workflow utilities to process files"
        required: true


jobs:
  DockerCleanup:
    uses: MagnusSletten/Databank/.github/workflows/DockerCleanup.yml@dev_cicd
    with:
      delete_images: false

  AddData:
    needs: DockerCleanup
    runs-on: nrec-large
    steps:
      - name: Pull Docker image
        run: |
            sudo docker pull nmrlipids/core
      
      - name: Computing new data
        run: |
            sudo docker run --rm \
              -e GITHUB_REPOSITORY="${{ github.repository }}" \
              -e BRANCH_NAME="${{ inputs.start_clean_branch}}" \
              -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
              -e TARGET_BRANCH="${{ inputs.working_branch }}" \
              -e TQDM_DISABLE=True \
              nmrlipids/core \
              /bin/bash -c "git fetch && git checkout \$BRANCH_NAME && git pull && python Scripts/WorkflowScripts/DockerRunInstructions/GetNewData.py"
        
