on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:  

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    container:
      image: nmrlipids/core
      options: --user 1001:118
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ci_tests_improve-docker  

      - name: Run regression test suite
        run: ./runtests-regression.sh