name: Weekly Scheduled Tests

on:
  #schedule:
    # Runs every Monday at 12:00 UTC
  #  - cron: '0 12 * * 1'
  workflow_dispatch:

jobs:
  regression-tests:
    if: github.repository == 'NMRLipids/Databank'
    runs-on: ubuntu-latest
    container:
      image: nmrlipids/core
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Install package and update dependencies
        run: |
          pip install -e . -r Scripts/DatabankLib/requirements-dev.txt

      - name: Run regression test suite as unprivileged user
        run: |
          # use runuser to switch to the 'runner' account you created in the image
          runuser -u runner -- ./runtests-regression.sh
