name: Test Regression Workflow

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:  # also allow manual runs

jobs:
  regression-tests:
    runs-on: ubuntu-latest
    container:
      image: nmrlipids/core
      options: --user 1001:118
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: test-branch  # specify your test branch name here

      - name: Run regression test suite
        run: ./runtests-regression.sh